swagger: "2.0"
info:
    title: order-producer
    version: 1.0.0
    description: sends orders to Kafka
consumes:
    - application/json
produces:
    - application/json
schemes:
    - http
paths: 
  /order:
    post:
      description: Creates new order
      tags:
        - order
      parameters: #TO BE SPECIFIED 
        - name: id
          in: body
          description: Unique identifier for the order
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
                example: "12345"
              items:
                type: array
                items:
                  type: object
                  properties:
                    productId:
                      type: string
                      example: "A1B2C3"
                    quantity:
                      type: integer
                      example: 1
      responses:
        '200':
          description: Successfully created order
        '400':
          description: Bad request, e.g., missing required fields
        '500':
          description: Internal server error`
